### ISSUE TITLE
PhaseDiagram.get_equilibrium_reaction_energy no longer works for ComputedEntry

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#1985]
**Describe the bug**
`PhaseDiagram.get_equlibrium_reaction_energy()` fails when called on a stable entry from the phase diagram, and raises

```ValueError: None is unstable, the equilibrium reaction energy is available only for stable entries```

**To Reproduce**
```
with MPRester() as m:
    entries = m.get_entries_in_chemsys("Zn-S")

pd = PhaseDiagram(entries)
pd.get_equilibrium_reaction_energy([e for e in pd.stable_entries][0])
```

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 2020.10.9

**Additional context**
The problem is caused by `entry.normalize(inplace=False)`, here:
https://github.com/materialsproject/pymatgen/blob/055805bc5e58a9951add78c441f5cb275da60679/pymatgen/analysis/phase_diagram.py#L665

`self.get_stable_entries_normed()` is populated by calling `entry.normalize(inplace=False)`, which creates copies of each entry. `entry.normalize(inplace=False)` creates _another_ copy of the entry that is not in the list.

I am working on a fix.

**Comment by rkingsbury** [comment]
@shyamd  feel free to add anything I missed

**Comment by rkingsbury** [comment]
I think this might actually be a bug in `.normalize`. The unittest we have passes, and it builds a `PhaseDiagram` from very simple `PDEntry` - they just have an energy and a composition, and
```
[e.normalize(inplace=False) for e in pd.stable_entries][0] in [e.normalize(inplace=False) for e in pd.stable_entries]
```
returns `True`. So somehow, using `ComputedEntry` instead of `PDEntry` causes this to fail.

**Comment by mkhorton** [comment]
The behavior of `ComputedEntry` did change recently, see https://github.com/materialsproject/pymatgen/commit/513eddb3fe32a43270df1f51cd58b93f9cc1aa9b

**Comment by rkingsbury** [comment]
I think this might be a subtle memory referencing thing. Using `ComputedEntry` (not `PDEntry`), I can do

```
>>> with MPRester() as m:
         entries = m.get_entries_in_chemsys("Zn-S")

>>> pd = PhaseDiagram(entries)
>>> [e.normalize(inplace=False) for e in pd.stable_entries][0] in pd.get_stable_entries_normed()
False
>>> [e.normalize(inplace=False) for e in pd.stable_entries][0].as_dict() == pd.get_stable_entries_normed()[0].as_dict()
True
```
and visual inspection of both dicts shows that the entries are identical.

In the case of a `PDEntry` that has far fewer attributes than a `ComputedEntry`, is it possible that Python is doing some sort of lazy referencing where it doesn't create a new copy of the entry because an identical one is already in memory? And then somehow it is NOT doing this for `ComputedEntry`?

**Comment by shyamd** [comment]
That last bit is because you're using Dict equals and i bet normalize isn't changing any of the values so the final dicts do have the same data. This also highlights that there might be an intrinsic issue where there should be a `__eq__` and `__hash__` defined if comparisons are being done on Entries.

**Comment by CompRhys** [comment]
@rkingsbury @shyamd I implemented `pd.get_stable_entries_normed()` which returns a list and so comparisons against it use `__eq__` rather than hash equality as a way to get around the fact that the `__hash__` for Entries is based on their id in memory rather than the object being considered. I think that if this is causing issues it would be valid just to remove the check in `get_equilibrium_reaction_energy` as it wasn't their before I added `quasi_e_from_hull`.

However, I think that setting a `__hash__` based on the object would be the preferable solution. The question is then do you hash based on some normalised representation or the inputted representation. I wanted to hash based on a normalised representation but that may lead to issues elsewhere in the code which is why @mkhorton advised me to try find a solution that avoided changing the hash when I added `get_quasi_e_from_hull`.

**Comment by rkingsbury** [comment]
Thanks for investigating this @CompRhys! You are correct that if I comment out the stability check, the bug goes away. However, the code always returns a reaction energy of zero because the next list equality check still fails.

```
    def get_equilibrium_reaction_energy(self, entry):
        """
        Provides the reaction energy of a stable entry from the neighboring
        equilibrium stable entries (also known as the inverse distance to
        hull).

        Args:
            entry (PDEntry): A PDEntry like object

        Returns:
            Equilibrium reaction energy of entry. Stable entries should have
            equilibrium reaction energy <= 0. The energy is given per atom.
        """
        # if entry.normalize(inplace=False) not in self.get_stable_entries_normed():
        #     raise ValueError(
        #         "{} is unstable, the equilibrium reaction energy is"
        #         "available only for stable entries.".format(entry)
        #     )

        if entry.is_element:
            return 0

        entries = [e for e in self.stable_entries if e.normalize(inplace=False) != entry.normalize(inplace=False)]
        modpd = PhaseDiagram(entries, self.elements)
        return modpd.get_decomp_and_e_above_hull(entry, allow_negative=True)[1]
```

I'm not well acquainted with `__eq__` vs hash equality. Which is normally invoked by Python when testing for membership in a list?

**Comment by shyamd** [comment]
So I spent a bit of time digging into this and here is my big picture recommendations:

1. Read https://hynek.me/articles/hashes-and-equality/
2. Make `Entry` a fully functioning class by having `Entry.energy` just return `Entry._energy`.
3. Thus`Entry` should have a `__hash__` and `__eq__` .
a. `__hash__` can just use the hash of the reduced composition
b. `__eq__` can check the composition are equals and the energies are equals within 1E-6
4. `PDEntry` `__eq__` should first check if the other is a PDEntry
a. if so, equality should be based on ID no?
b. if both IDs are `None`, then use`Entry.__eq__`

**Comment by CompRhys** [comment]
Wouldn't leaving `Entry` as an `ABC` but setting `__eq__` and `__hash__` as abstractmethods be an alternative? That would force careful consideration of what the ops do. 

I think that `PDEntry` needs to hash based on the object as the funky behaviour that arises from the hash for entries being based on mutable properties isn't fixed in terms of code functionality by the current hash (I can change the energy of something in `pd.stable_entries` such that it is unstable and it will remain in the set of stable entries) and things don't behave as expected (i.e. literal duplicates in the entry "set" used to test `PhaseDiagram` here due to the order they're loaded into memory hash(a)!=hash(b) even though a==b which is the condition of a hash).

In #1974 when stitching the `stable_entries` together in `PatchedPhaseDiagram` I end up with large numbers of duplicates that result in strange nominal decompositions. 

Could `Entry`, `PDEntry`, `ComputedEntry`, etc. reasonably be made immutable using `__slots__=[]` and making them child classes of `tuple`? Are there reasons to be able to change their properties once they have been declared?

**Comment by CompRhys** [comment]
The default object/user-defined-class `__hash__` and `__eq__` are 

```python 
    def __eq__(self, o) -> bool:
        # NOTE this is the default __eq__ of a user defined class
        # return object.__eq__(self, o)
        return id(self) == id(o)

    def __hash__(self) -> int:
        # NOTE this is the default __hash__ of a user defined class
        return hash(id(self)/16)
```

@rkingsbury As I understand list comparisons use `__eq__` and set comparisons use `__hash__` first then `__eq__`. This is why the hashing criteria can be weaker than the equality criteria.

It's interesting that it appears that the reason the `__hash__` is explicitly defined in `PDEntry` is that py3+ doesn't allow you to define `__eq__` explicitly without also defining the `__hash__`. The `__eq__` that was defined changes based on the object being mutable but the `__hash__` does not. This appears not to be great code practise and is probably the underlying cause of the issues both here and the ones I am having in getting the correct functionality in #1974  

Looking a little more if pymatgen were to move to having py3.7+ as it's req we could use https://docs.python.org/3/library/dataclasses.html with `frozen=True` to make the entries immutable (much cleaner than the `__slots__` approach - so much so that I would say it's not worth looking at the `__slots__` method as it's super hacky). Making them immutable would have implications on normalisation in-place and potentially in other parts of the code also.

**Comment by CompRhys** [comment]
@rkingsbury This is pretty much what it was before I added in the checks for normalised duplicates of stable entries.

```python
        if entry not in self.stable_entries:
            raise ValueError(
                "{} is unstable, the equilibrium reaction energy is"
                "available only for stable entries.".format(entry)
            )

        if entry.is_element:
            return 0

        entries = [e for e in self.stable_entries if e != entry]
        modpd = PhaseDiagram(entries, self.elements)
        return modpd.get_decomp_and_e_above_hull(entry, allow_negative=True)[1]
```

This code has the pathology that say you ran two calculations one with a supercell twice the unit cell of the other such that the energy and composition were scaled by 2. Only one of them would end up in the stable materials and have a non-zero reaction energy whilst the other would have a reaction energy of 0. It was like this for many years so I am not sure if this is an edge case that actually arises in user's workflows.

**Comment by shyamd** [comment]
That is sort of expected. PD is not expected to perform duplicate checking. The user is expected to take care of that. Maybe we could provide some sort of warning in that case though?

**Comment by CompRhys** [comment]
the check is necessary to pass the tests I wrote for `get_quasi_e_from_hull` using the testing entry set as it contains literal duplicates. I didn't necessarily see the problem of duplicates/scaled-duplicates arising in actual use but it does in the test set of entries so I had to work the edge case.

As the same edge case exists in `get_equilibrium_reaction_energy` (although it isn't being tested) I added the check into `get_equilibrium_reaction_energy` for parity. 

I wasn't aware at that time that `ComputedEntry` didn't use the same `__eq__` as `PDEntry`. I think it's best to revert the change and remove the check in `get_equilibrium_reaction_energy` but would really like to explicitly resolve the `__eq__` and `__hash__` issue as it also impacts #1974.

**Comment by rkingsbury** [comment]
I'd agree that we should resolve the discrepancy where, as I understand it, `__eq__` is different between `ComputedEntry` and `PDEntry` while `__hash__` is inherited from `PDEntry`.

I don't think it's practical to make `ComputedEntry` immutable, mainly because we need to be able to process them to apply energy corrections, which are stored in the `energy_adjustments` attribute. That attribute has to be mutable in order for corrections to work.

**Comment by CompRhys** [comment]
For `ComputedEntry` and `Entry` we have:

```python
    def __eq__(self, o) -> bool:
        # NOTE this is the default __eq__ of a user defined class
        return id(self) == id(o)

    def __hash__(self) -> int:
        # NOTE this is the default __hash__ of a user defined class
        return hash(id(self)/16)
```

For `PDEntry` we have:

```python
    def __eq__(self, other):
        # NOTE Scaled duplicates are not equal unless normalized separately
        if isinstance(other, self.__class__):
            return self.as_dict() == other.as_dict()
        return False

    def __hash__(self) -> int:
        # NOTE This hashing operation means that equivalent entries
        # hash to different values.
        return id(self)
```

so the hashes are slightly different but both based on the id.

I would propose for all we have something like:

```python
    def __hash__(self):
        data_md5 = hashlib.md5((
            f"{str(self.__class__.__name__)}"
            f"{self.composition.reduced_formula}"
            f"{self._energy}").encode('utf-8')
        ).hexdigest()
        return int(data_md5, 16)
```

as the hash.

The `__eq__` is less straightforward. I think @shyamd 's  idea of comparing on something cheap like the `entry_id` first instead of going straight to comparing the dictionary representations. However, in `PDEntry` there isn't the same separation between `entry_id` and `name`. If `name` isn't given then it's set to the `reduced_formula` so I wouldn't be sure what you would want to do there. Likewise for `ComputedEntry` equality based on the dictionary seems as though it might be quite heavy but I am not familiar with how `ComputedEntry` is used.

**Comment by rkingsbury** [comment]
I realized yesterday that this bug actually affects our ability to run `ThermoBuilder`, so I'd like to elevate it's priority. If we can come to a consensus here about the best fix I'll be happy to implement it.

From my perspective, I think we're looking for a solution that

- makes minimal changes to what exists now
- Puts as much of the logic in the `Entry` abstract base class as possible, to maximize consistency between different types of entries
- maintains the mutability of `ComputedEntry`, so that energy corrections and `normalize` continue to work the same way.

With respect to scaling compositions - I feel that there is a difference between a `ComputedEntry` with one composition (e.g., LiCl) and another with double its composition and energy (e.g., Li2Cl2), so those two should not be considered equal. Arguably, they could be considered equal as `PDEntry` for the purposes of `PhaseDiagram` construction, but from a practical perspective I think many users will build `PhaseDiagram` using `ComputedEntry` rather than `PDEntry`, so it would be best not to have too many inconsistencies in how we treat their `__eq__` and `__hash__`

**Comment by rkingsbury** [comment]
@mattmcdermott do you have any thoughts on this issue?

**Comment by CompRhys** [comment]
can we link this issue to #1974 and move the discussion there? The critical path there is also `__hash__` and `__eq__`. That PR is maybe mostly in a merge-able state but would appreciate feedback on the wider implications of the proposed changes made to `Entry` classes.

> With respect to scaling compositions - I feel that there is a difference between a ComputedEntry with one composition (e.g., LiCl) and another with double its composition and energy (e.g., Li2Cl2), so those two should not be considered equal.

I agree that they shouldn't be equal which was the my intention by adding the out of place normalization checks so they could be functionally equivalent when needed but otherwise not equal (this was how it worked for `PDEntry`. I have reverted the change that was causing this issue originally in `get_equilibrium_reaction_energy`. If users wanted this functionality with the normalization check they could still use `get_quasi_e_from_hull(stable_only=True)` which should also work for `ComputedEntry` given the changes to `__eq__` and `__hash__` - however, I should add a test for this probably.

**Comment by rkingsbury** [comment]
Sure, happy to move the discussion to #1974

**Comment by CompRhys** [comment]
@rkingsbury can this be closed?

**Comment by rkingsbury** [comment]
Fixed by #2014 . Thanks for all the patient work on this @CompRhys !
